version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "moviesdb"
      POSTGRES_USER: "userdb"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
